DROP TABLE IF EXISTS temperature;
DROP TABLE IF EXISTS humidity;
DROP TABLE IF EXISTS pressure;
DROP TABLE IF EXISTS windSpeed;

CREATE TABLE temperature (
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value FLOAT NOT NULL DEFAULT 0
);

CREATE TABLE humidity (
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value FLOAT NOT NULL DEFAULT 0
);

CREATE TABLE pressure (
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value FLOAT NOT NULL DEFAULT 0
);

CREATE TABLE windSpeed (
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value FLOAT NOT NULL DEFAULT 0
);