// Code generated by Arduino IoT Cloud

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
//#include "SSID_info.h"

const char THING_ID[] = "bd8cbadf-21f5-4406-aecb-1a12cf544365";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, use as key for WEP, or leave as empty string for unsecured network)

float humidity;
float pressure;
float temperature;
float windSpeed;
int uptime;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(humidity, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(pressure, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(windSpeed, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(uptime, READ, 60 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
